services:
  oracle-db:
    image: gvenzl/oracle-free:23-slim-faststart
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: ${ORACLE_SYS_USER_PASSWORD}
    volumes:
      - oracle-data:/opt/oracle/oradata
      - ./docker/oracle/init:/container-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 30

volumes:
  oracle-data:
